name: CD Workflow

on:
  workflow_call:
    inputs:
      PROJECT_NAME:
        required: true
        type: string

      PROJECT_CHANGED:
        required: true
        type: boolean

      IAC_CHANGED:
        required: true
        type: boolean

permissions: write-all

jobs:
  deploy-development-job:
    name: Deploy Development Job
    uses: ./.github/workflows/iac-workflow.yml
    with:
      PROJECT_NAME: '${{ inputs.PROJECT_NAME }}'
      PROJECT_CHANGED: ${{ inputs.PROJECT_CHANGED }}
      IAC_CHANGED: ${{ inputs.IAC_CHANGED }}
      ENVIRONMENT: Development
    secrets: inherit

  deploy-qa-job:
    name: Deploy QA Job
    needs: [deploy-development-job]
    uses: ./.github/workflows/iac-workflow.yml
    with:
      PROJECT_NAME: '${{ inputs.PROJECT_NAME }}'
      PROJECT_CHANGED: ${{ inputs.PROJECT_CHANGED }}
      IAC_CHANGED: ${{ inputs.IAC_CHANGED }}
      ENVIRONMENT: QA
    secrets: inherit

  deploy-production-job:
    name: Deploy Production Job
    needs: [deploy-qa-job]
    uses: ./.github/workflows/iac-workflow.yml
    with:
      PROJECT_NAME: '${{ inputs.PROJECT_NAME }}'
      PROJECT_CHANGED: ${{ inputs.PROJECT_CHANGED }}
      IAC_CHANGED: ${{ inputs.IAC_CHANGED }}
      ENVIRONMENT: Production
    secrets: inherit
